secrets:
  JWT_SECRET:
    file: '${PWD}/config/secrets/JWT_SECRET'
  SESSION_SECRET:
    file: '${PWD}/config/secrets/SESSION_SECRET'
  STORAGE_PASSWORD:
    file: '${PWD}/config/secrets/STORAGE_PASSWORD'
  STORAGE_ENCRYPTION_KEY:
    file: '${PWD}/config/secrets/STORAGE_ENCRYPTION_KEY'
  POSTGRES_ADMIN_PASSWORD:
    file: '${PWD}/config/secrets/POSTGRES_ADMIN_PASSWORD'

volumes:
  pgadmin-data:
  postgres-data:
  letsencrypt:

services:
  traefik:
    image: 'traefik:latest'
    container_name: 'traefik'
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--api.insecure=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--providers.docker.network=net"
      # - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      # - "--certificatesresolvers.myresolver.acme.email=TODO"
      # - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.service=api@internal"
      # - "traefik.http.routers.traefik.tls.certresolver=myresolver"
      # - "traefik.http.routers.traefik.middlewares=traefik-auth"
      # - "traefik.http.middlewares.traefik-auth.basicauth.users=TODO"

  authelia:
    container_name: 'authelia'
    image: 'docker.io/authelia/authelia:latest'
    restart: 'unless-stopped'
    networks:
      net:
        aliases: []
    expose:
      - 9091
    secrets:
      - 'JWT_SECRET'
      - 'SESSION_SECRET'
      - 'STORAGE_PASSWORD'
      - 'STORAGE_ENCRYPTION_KEY'
    environment:
      AUTHELIA_JWT_SECRET_FILE: '/run/secrets/JWT_SECRET'
      AUTHELIA_SESSION_SECRET_FILE: '/run/secrets/SESSION_SECRET'
      AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE: '/run/secrets/STORAGE_PASSWORD'
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: '/run/secrets/STORAGE_ENCRYPTION_KEY'
    volumes:
      - '${PWD}/config/authelia:/config'

  postgres:
    container_name: 'postgres'
    image: 'postgres:16'
    restart: unless-stopped
    shm_size: 128mb
    secrets: ['POSTGRES_ADMIN_PASSWORD']
    expose:
      - 5432
    networks:
      net:
        aliases: []
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_ADMIN_PASSWORD
      POSTGRES_USER: passmanAdmin
      POSTGRES_DB: passman
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
    labels:
      - "traefik.enable=false"

  pgadmin:
    container_name: 'pgadmin'
    image: dpage/pgadmin4:8
    restart: unless-stopped
    networks:
      net:
        aliases: []
    secrets: ['POSTGRES_ADMIN_PASSWORD']
    environment:
      PGADMIN_DEFAULT_EMAIL: passman@test.com
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/POSTGRES_ADMIN_PASSWORD
      PGADMIN_LISTEN_PORT: 8081
    expose:
      - 8081
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.localhost`)"
      - "traefik.http.routers.pgadmin.entrypoints=web"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=8081"

networks:
  net:
    name: 'net'